version: '3.7'

services:
  grafana:
    image: grafana/grafana-oss:8.5.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana:/var/lib/grafana
#      - type: bind
#        source: ./data/grafana
#        target: /grafana/static-data

  prometheus:
    #    network_mode: host
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#       - type: bind
#         source: ./data/prometheus
#         target: /prometheus/static-data
#         target: /prometheus/static-data
