{
 "title": "IDUnion",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "\"Bosch\",\"Bundesdruckerei\",\"Commerzbank\",\"siemens\",\"DeutscheBahn\",\"GS1Germany\",\"ING\",\"MainIncubator\",\"esatus_AG\",\"T-Labs\",\"regio_iT\",\"tubzecm\",\"Spherity_GmbH\",\"mgm_tp\",\".msg\""
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "$node Uptime",
   "type": "stat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "stat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  }
 ]
}