    global:
      scrape_interval: 15s
      evaluation_interval: 15s # Evaluate rules every 15 seconds.

    scrape_configs:
      - job_name: 'node-external'
        static_configs:
          - targets: ['localhost:9100']
            labels:
              group: 'prod-ext'

