    global:
      scrape_interval: 60s

      evaluation_interval: 60s # Evaluate rules every 60 seconds.


    scrape_configs:
      - job_name: 'node-external'
        static_configs:
          - targets: ['172.17.0.1:9100', '172.17.0.1:9101','172.17.0.1:9102', '172.17.0.1:9103']
            labels:
              group: 'prod-ext'
