@startuml

node "VON Network" as VON {
  [Node1] - [Node2]
  [Node1] - [Node3]
  [Node1] - [Node4]
  [Node2] - [Node1]
  [Node2] - [Node3]
  [Node2] - [Node4]
  [Node3] - [Node1]
  [Node3] - [Node2]
  [Node3] - [Node4]
}

[Metrics Engine]

database "Prometheus" {
  folder "Metrics" {
    [KPIs]
  }
}

interface Dashboard as Dashboard

[Metrics Engine] ..> VON : collect data
[Metrics Engine] --> Metrics
Dashboard ..> KPIs : visualize
@enduml